version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    networks:
      - net

  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8880:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

    networks:
      - net

  serverless:
    container_name: serverless
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: ["npm", "run", "start"]
    stdin_open: true
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./graphql:/api
    working_dir: /api
    networks:
      - net

volumes:
  db_data:

networks:
  net:
